version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - basa:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: iamalexandr/yamdb_final
    restart: always
    volumes:
      - ../api_yamdb/static:/app/static/
      - ../api_yamdb/temlates:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - - ../api_yamdb/static:/var/html/static/
      - ../api_yamdb/temlates:/var/html/media/
    depends_on:
      - web

volumes:
  basa:
  static_value:
  media_value:
    driver: local
    driver_opts:
      type: none
      device: /app/static/
      o: bind