
version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: iamalexandr/api_yamdb:latest
    restart: always
    volumes:
      - $PWD/../api_yamdb/static:/app/static/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/../api_yamdb/templates:/var/html/redoc/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  database:
  static_value:
  media_value:
